# All about Qubits















Author: [Monit Sharma](https://github.com/MonitSharma)
LinkedIn: [Monit Sharma](https://www.linkedin.com/in/monitsharma/)
Twitter: [@MonitSharma1729](https://twitter.com/MonitSharma1729)
Medium : [MonitSharma](https://medium.com/@_monitsharma)

### Learning Objectives



*   Write down the mathematical description of a qubit in two different notation
*   Define and give examples of what it measn for a quantum system to be in a **superposition** of states.
*  State the relation between **amplitudes** and measurement outcome **probabilities** and what it means to be *normalized*

* Explain how operations are mathematically applied to qubit states.



Quantum Computers are an emerging technology with amazing potential to solve the problems that are intractable even on todays biggest supercomputers. 

--- 

Regulat computers will be refered to as **classical computers** and they represent information in *bits*. A bit is a binary value. It can be either $0$ or $1$ and this is associtaed to something physical being in two different states. For example: A voltage passing through a electric component can be used to represent bits. We can chose the threshold value of the voltage and denote any voltage over that threshold as a bit in state $1$ and similary any voltage below that in $0$






![](https://codebook.xanadu.ai/pics/voltage_threshold.svg)



-----------


The power of quantum computers comes from the **different ways in which they represent and manipulate information**. 

Quantum computers use special bits, called quantum bits or **qubits**. As with bits , qubits  also correspond to something physical.


--------

Quantum computing is the manipulation of qubits to solve problems.  In this notebook you'll learn about the mathematical underpinnings of quantum computing. The key ingredients we need are:




*   a mathematical representation of a qubit's state
*   a means of measuring a qubit to determine what state it is in
*   a way of manipulating the state to perform computation.




#### Codercise I.1.1 
Suppose we are given an unnormalized quantum state:

$$ |\psi⟩ = \alpha |0⟩ + β|1⟩$$
where 
$$ |\alpha|^2 + |\beta|^2 \ne 1$$

We can turn this into an equivalent , valid quantum state by *normalizing* it.

Write a function that normalizes the state:

In [1]:
import numpy as np

In [2]:
# Here are the vector representations of |0> and |1>, for convenience
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.
    
    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.
        
    Returns:
        array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """
    arr = [alpha, beta]
    arr = arr / np.linalg.norm(arr)
    
    return arr
    
    
    
    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    
    # RETURN A VECTOR
    pass 


In [3]:
normalize_state(0.83,0.33)

array([0.9292468 , 0.36945957])

#### Codercise I.1.2 

Write a function to compute the inner product between two arbitrary states. Then use it to verify that $|0⟩$ and $|1⟩$ form an **orthonormal basis**

In [4]:
def inner_product(state_1, state_2):
    """Compute the inner product between two states.
    
    Args:
        state_1 (array[complex]): A normalized quantum state vector
        state_2 (array[complex]): A second normalized quantum state vector
        
    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """
 
    

    # COMPUTE AND RETURN THE INNER PRODUCT

    return  np.dot((state_1), np.conj(state_2))


# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")


<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1


#### Codercise I.1.3

The function below takes a quantum state vector as input. Complete the function to simulate the outcomes of an arbitrary number of quantum measurements

In [7]:
def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (array[complex]): A normalized qubit state vector. 
        num_meas (int): The number of measurements to take
        
    Returns:
        array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability 
        distribution defined by the input state.
    """

   
    
    return np.random.choice(2,num_meas, p =[np.abs(state[0])**2, np.abs(state[1])**2])
    
    # COMPUTE THE MEASUREMENT OUTCOME PROBABILITIES

    # RETURN A LIST OF SAMPLE MEASUREMENT OUTCOMES
 
    pass


In [8]:
state = np.array([0.6,0.8])
U = np.array([[0,1],[1,0]])

In [9]:
measure_state(state,10)

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 1])

#### Codercise I.1.4 
Complete the functions below to apply the provided quantum operation `U` to an input state

In [10]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (array[complex]): A normalized quantum state vector. 
        
    Returns:
        array[complex]: The output state after applying U.
    """

    
    return np.dot(U,state)

    # APPLY U TO THE INPUT STATE AND RETURN THE NEW STATE
    pass


In [11]:
apply_u(state)

array([ 0.98994949, -0.14142136])

#### Codercise I.1.5

Use the functions below to simulate a quantum algorithm that does:



1.   Initialize the qubit in state $|0⟩$
2.   Apply the provided operation `U`

3.   Simulate measuring the output state 1000 times



In [12]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    
    return np.array([1,0])

    # PREPARE THE STATE |0>   
    pass


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """

    ##################
    # YOUR CODE HERE #
    ##################
    state = np.array([1,0])
    state1 = apply_u(state)
    
    return measure_state(state1,100)

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    pass


In [13]:
quantum_algorithm()

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1])

Solutions by [Monit Sharma](https://github.com/MonitSharma)